### ISSUE TITLE
好搞笑哦，你这东西测过吗？

### ISSUE THREAD

**Issue by lhmouse** [lucklove/ahttpd#9]
https://github.com/lucklove/shttpd/blob/master/src/client.cc#L36

user:pass 真是亮瞎狗眼。

**Comment by lucklove** [comment]
关于HTTP Basic Authentication我参考的http://smalltalllong.iteye.com/blog/912046, 如果不对请指教  
关于测试， 我用ab测试过并发性，另外example在我的linux(kernel 3.19.3-3)上也能正常运行，unit测试暂时没有，过一阵闲一点会做(个人比较懒而已)  
那个@并不是user@pass, 而是user:pass@server, 只是在regex里并没有把user:pass分开，而是作为同一个子表达式提取的, 实际上user:pass可以是任意不包含@的东西, 所以  
-  ./client http://user:pass@www.xxx.com -> 提取出"user:pass"  
- ./client http://user@www.xxx.com -> 提取出"user"  
- ./client http://:pass@www.xxx.com -> 提取出":pass"  

实际上curl的工作原理也是这样的，具体测试方案如下(交替使用curl和example中的client, 并观察Authorization头):  
netcat -l -p 8888  
- curl "luck:luck:luck@127.0.0.1:8888" 
- ./client GET "luck:luck:luck@127.0.0.1:8888"  
  结果Authorization相同  
  ----------------------------------------------------------------  
- curl ":luck@127.0.0.1:8888"
- ./client GET ":luck@127.0.0.1:8888"  
  curl没有Authorization, client的Authorization: Basic Omx1Y2s=  
  -----------------------------------------------------------------  
-  curl "luck@luck@127.0.0.1:8888"  
- ./client GET "luck@luck@127.0.0.1:8888"  
  均无法解析地址  

以上

**Comment by lucklove** [comment]
另外，现在是没有把user:pass分开的，只是单纯把"user:pass"这个字符串提取出来base64,而已，所以
- ./client http://user@www.xxx.com -> 提取出"user"进行base64  
- ./client http://:pass@www.xxx.com -> 提取出":pass"进行base64

**Comment by lhmouse** [comment]
敢不敢写在外面，非放在 URL 里面啊？

**Comment by lucklove** [comment]
不一定需要放在url里面，uri中的user:pass是可选的。  
要是不想在uri里放user:pass可以在example中的https://github.com/lucklove/shttpd/blob/master/example/client/client.cc#L25
加上 req->basicAuth("user:pass")；(加在if前面)

**Comment by fvck** [comment]
哈哈，还真是狗眼，uri的component有哪些都不知道就出来喷人，要喷也要注意别给自己挖坑啊，比如你可以喷他uri component没支持全，喷支持多了是什么鬼

**Comment by lhmouse** [comment]
@fvck 

是不是 URI 在这里有什么关系。把用户名和密码写进 URI，这做法放在 curl 上就算了，既然做成面向开发者的函数，这就是 _不恰当_ 的。至于那个正则拿出来解析 URI 的纯粹是醉了。

即使是服务端实现，也不是直接把用户名丢 URI 里面的。这种做法除了在 CLI 里敲起来省事以外乏善可陈。

**Comment by lucklove** [comment]
@lhmouse  
你看到的那个URI解析是在client里面，server是看不到uri里的用户名和密码的，只能看到头里面的Authorization字段。  
至于为什么在client直接写进uri,  仅仅是为了使用方便而已， 比如在GET需要HTTP Basic验证的信息时，只需要client->request("GET", "user:pass@server[:port][/path][?query]"， response_handler)即可，如果不支持该特性，则需要提供第四个参数(request_handler）来对请求报文加上Authorization头。  
另外用正则解析URI可以省不少代码量，这样有什么问题吗？

**Comment by lhmouse** [comment]
@lucklove 
1. 在 URI 里写用户名和密码，然后用正则往外抽，既不是优雅的设计，也不高效；
2. 除非有互操作性的需要，少用正则，又慢又不讨好；
3. 补充一下，一般的 HTTP client 实现应该在收到 401 状态码以后才发 user pass。

**Comment by lucklove** [comment]
@lhmouse 
1.用正则不高效我赞同，这里确实是个偷懒的实现  
2.和第一点重复  
3.关于第三点， 大部分CLI工具(如curl)的做法和通常的client(如google-chrome)不大一样，比如http://api.minicloud.com.cn/statuses/friends_timeline.xml  这个网址，用一般浏览器是会让你输入用户名和密码的，然而curl, 该是什么就是什么，如实返回而已， 如你所说shttpd里的client是面向开发者的， 所以选择CLI类似的做法要比后者提供给用户的空间大  
因此，在知道对方需要验证的情况下，总将user&pass填写到uri中会方便很多(考虑到app server访问的大多数第三方网站都是知道对方是否需要验证的）
